{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-tester
  annotations:
    traefik.ingress.kubernetes.io/redirect-to-https: "false"
    traefik.ingress.kubernetes.io/request-headers: "X-ForwardedProto=http"
spec:
  ingressClassName: traefik 
  rules:
  - host: load-tester.local 
    http:
      paths:
      - path: / 
        pathType: Prefix 
        backend:
          service:
            name: load-tester
            port:
              number: {{ $.Values.service.port }}
{{- end }}
